apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-spring-boot
spec:
  selector:
    matchLabels:
      app: monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: harbor.local/test/monitor:monitor
          ports:
            - containerPort: 8083
          imagePullPolicy: IfNotPresent