spring:
  datasource:
    url: jdbc:mysql://47.106.111.7:3306/erlangtest?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: erlangtest
    password: erlangtest
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: 192.168.8.138
#    password: 123456?
#    port: 8888


#Krkrpa config
krpano:
  basePath: D:/Uninstalled/krpano/
  enginePath: D:/Uninstalled/krpano/krpanotools.exe
  imageSourcePath: D:/Uninstalled/krpano/imageSource/
  productionsPath: D:/Uninstalled/krpano/productions/
  sceneConfigPath: D:/Uninstalled/krpano/templates/


#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
