spring:
  datasource:
    url: jdbc:mysql://110.42.222.129:3306/platform_monitor?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: gao1399677
    driver-class-name: com.mysql.cj.jdbc.Driver

monitor:
  url: http://192.168.8.136:8080/