server:
  port: 9875
  servlet:
    context-path: /monitor
  tomcat:
    accesslog:
      directory: access
      enabled: true
      pattern: common
      prefix: access_log
      suffix: .log
    basedir: ./logs/pano/

spring:
  web:
    resources:
      static-locations: classpath:/static, file:${krpano.productionsPath}, file:${krpano.iconPath}
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 3600000
      maximum-pool-size: 100
      minimum-idle: 50
      validation-timeout: 3000
  servlet:
    multipart:
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.ykx.marketing.po
  mapper-locations: classpath*:com.ykx.marketing.mapper/*.xml

