spring:
  datasource:
    url: jdbc:mysql://47.106.111.7:3306/erlangtest
    username: erlangtest
    password: erlangtest
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: 192.168.8.138
#    password: 123456?
#    port: 8888


#Krkrpa config
krpano:
  basePath: /home/krpano/
  enginePath: /home/krpano/krpanotools
  imageSourcePath: /home/krpano/imageSource/
  productionsPath: /home/krpano/productions/
  sceneConfigPath: /home/krpano/templates/
  iconPath: /opt/filetest/



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
