server:
  port: 9875
  servlet:
    context-path: /platform
  tomcat:
    accesslog:
      directory: access
      enabled: true
      pattern: common
      prefix: access_log
      suffix: .log
    basedir: ./logs/monitor/

spring:

  profiles:
    active: prod

