spring:
  datasource:
    dynamic:
      primary: master
      strict: false #启动不检查
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/vrcase?serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vr
          password: 123456
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/vrcase?serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vr
          password: 123456

#  redis:
#    host: 192.168.8.138
#    password: 123456?
#    port: 8888


#Krkrpa config
krpano:
  basePath: D:/project/krpano/
  enginePath: D:/project/krpano/krpanotools.exe
  imageSourcePath: D:/project/krpano/imageSource/
  productionsPath: D:/project/krpano/productions/
  sceneConfigPath: D:/project/krpano/templates/
  iconPath: D:/filevr/



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
